export const countries = [
    { name: 'فلسطين', code: 'PS', dial: '+970', flag: '🇵🇸' },
    { name: 'السعودية', code: 'SA', dial: '+966', flag: '🇦' },
    { name: 'الإمارات', code: 'AE', dial: '+971', flag: '🇦' },
    { name: 'الكويت', code: 'KW', dial: '+965', flag: '🇰🇼' },
    { name: 'قطر', code: 'QA', dial: '+974', flag: '🇶🇦' },
    { name: 'البحرين', code: 'BH', dial: '+973', flag: '🇧🇭' },
    { name: 'عُمان', code: 'OM', dial: '+968', flag: '🇴🇲' },
    { name: 'الأردن', code: 'JO', dial: '+962', flag: '🇯🇴' },
    { name: 'لبنان', code: 'LB', dial: '+961', flag: '🇱🇧' },
    { name: 'سوريا', code: 'SY', dial: '+963', flag: '🇸🇾' },
    { name: 'العراق', code: 'IQ', dial: '+964', flag: '🇮🇶' },
    { name: 'مصر', code: 'EG', dial: '+20', flag: '🇪🇬' },
    { name: 'ليبيا', code: 'LY', dial: '+218', flag: '🇱🇾' },
    { name: 'تونس', code: 'TN', dial: '+216', flag: '🇹🇳' },
    { name: 'الجزائر', code: 'DZ', dial: '+213', flag: '🇩🇿' },
    { name: 'المغرب', code: 'MA', dial: '+212', flag: '🇦' },
    { name: 'السودان', code: 'SD', dial: '+249', flag: '🇸🇩' },
    { name: 'اليمن', code: 'YE', dial: '+967', flag: '🇾🇪' },
    { name: 'الولايات المتحدة', code: 'US', dial: '+1', flag: '🇺🇸' },
    { name: 'كندا', code: 'CA', dial: '+1', flag: '🇨🇦' },
    { name: 'بريطانيا', code: 'GB', dial: '+44', flag: '🇧' },
    { name: 'ألمانيا', code: 'DE', dial: '+49', flag: '🇩🇪' },
    { name: 'فرنسا', code: 'FR', dial: '+33', flag: '🇫🇷' },
    { name: 'إيطاليا', code: 'IT', dial: '+39', flag: '🇮🇹' },
    { name: 'إسبانيا', code: 'ES', dial: '+34', flag: '🇪🇸' },
    { name: 'تركيا', code: 'TR', dial: '+90', flag: '🇹🇷' },
    { name: 'روسيا', code: 'RU', dial: '+7', flag: '🇷🇺' },
    { name: 'الصين', code: 'CN', dial: '+86', flag: '🇨🇳' },
    { name: 'اليابان', code: 'JP', dial: '+81', flag: '🇯🇵' },
    { name: 'كوريا الجنوبية', code: 'KR', dial: '+82', flag: '🇰🇷' },
    { name: 'الهند', code: 'IN', dial: '+91', flag: '🇮🇳' },
    { name: 'باكستان', code: 'PK', dial: '+92', flag: '🇵🇰' },
    { name: 'بنغلاديش', code: 'BD', dial: '+880', flag: '🇧🇩' },
    { name: 'أفغانستان', code: 'AF', dial: '+93', flag: '🇦🇫' },
    { name: 'إيران', code: 'IR', dial: '+98', flag: '🇮🇷' },
    { name: 'ماليزيا', code: 'MY', dial: '+60', flag: '🇾' },
    { name: 'إندونيسيا', code: 'ID', dial: '+62', flag: '🇮🇩' },
    { name: 'الفلبين', code: 'PH', dial: '+63', flag: '🇵🇭' },
    { name: 'تايلاند', code: 'TH', dial: '+66', flag: '🇹🇭' },
    { name: 'فيتنام', code: 'VN', dial: '+84', flag: '🇻🇳' },
    { name: 'أستراليا', code: 'AU', dial: '+61', flag: '🇦🇺' },
    { name: 'نيوزيلندا', code: 'NZ', dial: '+64', flag: '🇳' },
    { name: 'البرازيل', code: 'BR', dial: '+55', flag: '🇧🇷' },
    { name: 'الأرجنتين', code: 'AR', dial: '+54', flag: '🇦🇷' },
    { name: 'المكسيك', code: 'MX', dial: '+52', flag: '🇲🇽' },
    { name: 'جنوب أفريقيا', code: 'ZA', dial: '+27', flag: '🇦' },
    { name: 'نيجيريا', code: 'NG', dial: '+234', flag: '🇳🇬' },
    { name: 'كينيا', code: 'KE', dial: '+254', flag: '🇰' },
    { name: 'إثيوبيا', code: 'ET', dial: '+251', flag: '🇪🇹' },
    { name: 'الصومال', code: 'SO', dial: '+252', flag: '🇸🇴' }
];
